const fs = require('fs');
const path = require('path');

// 递归遍历目
function walkDir(dir, callback) {
    if (!fs.existsSync(dir)) return;
    fs.readdirSync(dir).forEach(f => {
        let dirPath = path.join(dir, f);
        let isDirectory = fs.statSync(dirPath).isDirectory();
        isDirectory ? walkDir(dirPath, callback) : callback(path.join(dir, f));
    });
}

const rootDir = path.join(__dirname, '../rulesets');

console.log(`Scanning directory: ${rootDir}`);

walkDir(rootDir, (filePath) => {
    if (path.extname(filePath) === '.list') {
        try {
            const content = fs.readFileSync(filePath, 'utf8');
            const lines = content.split(/\r?\n/);
            const rules = [];

            lines.forEach(line => {
                // 移除行内注释
                const cleanLine = line.split('#')[0].split(';')[0].trim();
                if (cleanLine) {
                    rules.push(cleanLine);
                }
            });

            if (rules.length > 0) {
                // 生成 YAML payload 格式
                // 确保对单引号进行转义（虽然规则中很少有单引号，但以防万一）

                const relativePath = path.relative(path.join(__dirname, '..'), filePath);
                const generatedTime = new Date().toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' });

                const header = [
                    '# CONTENT-TYPE: CLASH-RULESET',
                    '# GENERATED BY: ACL4ALL Automated Script',
                    `# SOURCE FILE: ${relativePath}`,
                    `# GENERATED AT: ${generatedTime}`,
                    `# RULE COUNT: ${rules.length}`,
                ].join('\n');

                const yamlRules = rules.map(r => `  - '${r.replace(/'/g, "''")}'`).join('\n');
                const yamlContent = `${header}\npayload:\n${yamlRules}\n`;

                const yamlPath = filePath.replace('.list', '.yaml');
                fs.writeFileSync(yamlPath, yamlContent);
                console.log(`Generated: ${path.basename(yamlPath)} (${rules.length} rules)`);
            }
        } catch (error) {
            console.error(`Error processing ${filePath}:`, error);
        }
    }
});
